import {
  faBolt,
  faChild,
  faDumbbell,
  faHeartPulse,
  faMountain,
  faPersonBiking,
  faPersonPraying,
  faPersonRunning,
  faPersonSkating,
  faPersonSwimming,
  faPersonWalking,
  faSpa,
} from '@fortawesome/free-solid-svg-icons';

export const RUTINE_TYPE = [
  {
    label: 'Gym',
    value: 'GYM',
    icon: faDumbbell,
    color: '#9B65FC',
    background: '#36294E',
  },
  {
    label: 'Cardio',
    value: 'CARDIO',
    icon: faHeartPulse,
    color: '#ED6455',
    background: '#4E2A25',
  },
  {
    label: 'Crossfit',
    value: 'CROSSFIT',
    icon: faBolt,
    color: '#F5C451',
    background: '#4E4425',
  },
  {
    label: 'Funcional',
    value: 'FUNCTIONAL',
    icon: faPersonWalking,
    color: '#5FD3C4',
    background: '#1F4640',
  },
  {
    label: 'Pilates',
    value: 'PILATES',
    icon: faSpa,
    color: '#F49AC2',
    background: '#4A2638',
  },
  {
    label: 'Yoga',
    value: 'YOGA',
    icon: faPersonPraying,
    color: '#B18CF0',
    background: '#332246',
  },
  {
    label: 'Natación',
    value: 'SWIMMING',
    icon: faPersonSwimming,
    color: '#5AB6F2',
    background: '#1E3A4E',
  },
  {
    label: 'Running',
    value: 'RUNNING',
    icon: faPersonRunning,
    color: '#20D6D1',
    background: '#164546',
  },
  {
    label: 'Ciclismo',
    value: 'CYCLING',
    icon: faPersonBiking,
    color: '#F5945C',
    background: '#4E3420',
  },
  {
    label: 'Escalada',
    value: 'CLIMBING',
    icon: faMountain,
    color: '#8DA3F0',
    background: '#22264E',
  },
  {
    label: 'Skateboard',
    value: 'SKATEBOARD',
    icon: faPersonSkating,
    color: '#F55C7A',
    background: '#4E1F2A',
  },
  {
    label: 'Calistenia',
    value: 'CALISTENIA',
    icon: faChild,
    color: '#66D97E',
    background: '#1F4E2A',
  },
];
